---
kind: pipeline
type: docker
name: default

steps:
- name: Build
  image: plugins/docker
  settings:
    repo: czoksu/lazydev
    username:
      from_secret: DOCKERHUB_USR
    password:
      from_secret: DOCKERHUB_PWD
    tags:
    - latest

- name: Deploy
  image: google/cloud-sdk
  commands:
  - "echo $$GAE_CREDENTIALS > /tmp/creds.json"
  - "gcloud auth activate-service-account drone-201@galvanic-circle-213007.iam.gserviceaccount.com --keyfile=/tmp/creds.json"
  - "gcloud app deploy app.yaml"
