---
kind: pipeline
type: docker
name: default

steps:
- name: Deploy
  image: google/cloud-sdk
  environment:
    GCP_SECRET:
      from_secret: GAE_CREDENTIALS
    CLOUDSDK_CORE_PROJECT: galvanic-circle-213007
  commands:
  - "printf \"%s\" \"$$GCP_SECRET\" > /tmp/creds.json"
  - "gcloud auth activate-service-account drone-201@galvanic-circle-213007.iam.gserviceaccount.com --key-file=/tmp/creds.json"
  - "gcloud app create --region=us-central --project=galvanic-circle-213007 "
  - "gcloud app deploy app.yaml"

- name: Build
  image: plugins/docker
  settings:
    repo: czoksu/lazydev
    username:
      from_secret: DOCKERHUB_USR
    password:
      from_secret: DOCKERHUB_PWD
    tags:
    - latest

